### ISSUE TITLE
非常棒的项目呀

### ISSUE THREAD

**Issue by HarryChen0506** [lizhiqianduan/ycc#1]
我最近也想自己造一个canvas引擎的轮子玩玩，从你这里获得了不少好的idea。感谢作者:-）

**Comment by codemyhappy** [comment]
@HarryChen0506 感谢支持！轮子做出来看看哦

**Comment by HarryChen0506** [comment]
好的，目前还在设计阶段，主要参考库有 thee.js, fabric.js, two.js，还有你的这个

**Comment by codemyhappy** [comment]
挺好玩的！就是从零开始费时间，加油哦

**Comment by HarryChen0506** [comment]
谢谢！本意是想用来学习提升的，难度其实还是不小的，希望能坚持下去吧 :-）

**Comment by HarryChen0506** [comment]
乘假期终于赶出来了一个小版本, 感谢哟.  https://github.com/HarryChen0506/malyan
